name: docs

on:
  push:
    branches: [ master ]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependency
        run: |
          pip install -r requirements-dev.txt
          pip install -r requirements.txt
      - name: Build documentation
        run: make docs
      - name: Deploy
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html/
